version: '3.8'

services:
  master:
    build:
      context: ./master
      dockerfile: Dockerfile
      args:
        - USE_GPU=0
    ports:
      - "8000:8000"
    volumes:
      - ./master:/app
      - model_cache:/app/model_cache
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=master.settings
      - SECRET_KEY=your-secret-key-change-in-production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - MODEL_CACHE_DIR=/app/model_cache
      - USE_GPU=0
    depends_on:
      - redis
    restart: unless-stopped

  worker1:
    build:
      context: ./worker
      dockerfile: Dockerfile
      args:
        - USE_GPU=0
    ports:
      - "5001:8000"
    volumes:
      - ./worker:/app
      - model_cache:/app/model_cache
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=worker.settings
      - SECRET_KEY=worker-secret-key-change-in-production
      - MODEL_CACHE_DIR=/app/model_cache
      - USE_GPU=0
      - AUTH_ENABLED=0
      - AUTH_KEY=default-auth-key-change-in-production
    restart: unless-stopped

  worker2:
    build:
      context: ./worker
      dockerfile: Dockerfile
      args:
        - USE_GPU=0
    ports:
      - "5002:8000"
    volumes:
      - ./worker:/app
      - model_cache:/app/model_cache
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=worker.settings
      - SECRET_KEY=worker-secret-key-change-in-production
      - MODEL_CACHE_DIR=/app/model_cache
      - USE_GPU=0
      - AUTH_ENABLED=0
      - AUTH_KEY=default-auth-key-change-in-production
    restart: unless-stopped

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  model_cache:
  redis_data:
